slogo_team06: ui.TurtleView Class Reference
ui.TurtleView Class Reference
Public Member Functions
TurtleView (Image imageIn, Canvas canvasIn, double xIn, double yIn, StackPane canvasHolder, Pen penIn)
void update (Observable o, Object arg)
ImageView getImageView ()
void setImage (Image image)
void setTurtleVisible (boolean invisible)
DoubleProperty getHeading ()
Private Member Functions
void addTurtle (ImageView turtle)
void draw (double x1, double y1, double x2, double y2, boolean hasTurtle)
void updateRotation (boolean hasTurtle)
Private Attributes
ImageView myImageView
Canvas myCanvas
double canvasCenterX
double canvasCenterY
DoubleProperty myHeading
StackPane myCanvasHolder
boolean turtleIsVisible
Pen myPen
Detailed Description
Definition at line 15 of file TurtleView.java.
Constructor & Destructor Documentation
ui.TurtleView.TurtleView (Image imageIn, Canvas canvasIn, double xIn, double yIn, StackPane canvasHolder, Pen penIn)
Definition at line 25 of file TurtleView.java.
References ui.TurtleView.addTurtle().
Member Function Documentation
void ui.TurtleView.addTurtle (ImageView turtle) private
Adds the imageView to the CanvasHolder
Parameters
ID : ID of turtle
turtle : Image of turtle
Definition at line 56 of file TurtleView.java.
Referenced by ui.TurtleView.TurtleView().
void ui.TurtleView.draw (double x1, double y1, double x2, double y2, boolean hasTurtle) private
Draws the Turtle and Line
Parameters
x1 : Old X value
y1 : Old Y value
x2 : New X value
y2 : New Y value
hasLine : Pen is down
hasTurtle : Turtle is visible
Definition at line 78 of file TurtleView.java.
References ui.Pen.draw(), and ui.TurtleView.updateRotation().
Referenced by ui.TurtleView.update().
DoubleProperty ui.TurtleView.getHeading ()
Definition at line 163 of file TurtleView.java.
References ui.TurtleView.myHeading.
Referenced by ui.elements.TPropertiesElement.makeTurtleHeadingBox().
ImageView ui.TurtleView.getImageView ()
Definition at line 134 of file TurtleView.java.
References ui.TurtleView.myImageView.
void ui.TurtleView.setImage (Image image)
Re-sets up the imageView with a new Image, used when a new image is selected
Parameters
image
Definition at line 144 of file TurtleView.java.
Referenced by ui.elements.TPropertiesElement.selectAndChangeTurtleImage().
void ui.TurtleView.setTurtleVisible (boolean invisible)
Definition at line 159 of file TurtleView.java.
Referenced by ui.elements.TPropertiesElement.init().
void ui.TurtleView.update (Observable o, Object arg)
Observer update method
Definition at line 110 of file TurtleView.java.
References ui.TurtleView.draw(), model.Turtle.getCleared(), model.Turtle.getHeading(), model.Turtle.getVisibility(), model.Turtle.getX(), model.Turtle.getY(), and ui.TurtleView.updateRotation().
void ui.TurtleView.updateRotation (boolean hasTurtle) private
Definition at line 101 of file TurtleView.java.
Referenced by ui.TurtleView.draw(), and ui.TurtleView.update().
Member Data Documentation
double ui.TurtleView.canvasCenterX private
Definition at line 18 of file TurtleView.java.
double ui.TurtleView.canvasCenterY private
Definition at line 19 of file TurtleView.java.
Canvas ui.TurtleView.myCanvas private
Definition at line 17 of file TurtleView.java.
StackPane ui.TurtleView.myCanvasHolder private
Definition at line 21 of file TurtleView.java.
DoubleProperty ui.TurtleView.myHeading private
Definition at line 20 of file TurtleView.java.
Referenced by ui.TurtleView.getHeading().
ImageView ui.TurtleView.myImageView private
Definition at line 16 of file TurtleView.java.
Referenced by ui.TurtleView.getImageView().
Pen ui.TurtleView.myPen private
Definition at line 23 of file TurtleView.java.
boolean ui.TurtleView.turtleIsVisible private
Definition at line 22 of file TurtleView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/ui/TurtleView.java