slogo_team06: parser.GroupStartCase Class Reference
parser.GroupStartCase Class Reference
Public Member Functions
GroupStartCase (TreeWrapper wrapper, List< String > input)
void recurse (CommandTreeNode root)
Private Attributes
TreeWrapper wrapper
List< String > myInput
Detailed Description
A class that deals with when the word is the start of a group.
Author
Kei Yoshikoshi
Definition at line 11 of file GroupStartCase.java.
Constructor & Destructor Documentation
parser.GroupStartCase.GroupStartCase (TreeWrapper wrapper, List< String > input)
Definition at line 15 of file GroupStartCase.java.
References parser.GroupStartCase.wrapper.
Member Function Documentation
void parser.GroupStartCase.recurse (CommandTreeNode root)
recurse method to generate the tree
Parameters
root
Implements parser.Cases.
Definition at line 25 of file GroupStartCase.java.
References parser.CommandTreeNode.add(), parser.TreeWrapper.getIndex(), parser.CommandTreeNode.getName(), parser.CommandTreeNode.getType(), parser.TreeWrapper.incrementIndex(), parser.TreeWrapper.printTestStatements(), and parser.TreeWrapper.recurse().
Member Data Documentation
List<String> parser.GroupStartCase.myInput private
Definition at line 13 of file GroupStartCase.java.
TreeWrapper parser.GroupStartCase.wrapper private
Definition at line 12 of file GroupStartCase.java.
Referenced by parser.GroupStartCase.GroupStartCase().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/parser/GroupStartCase.java