slogo_team06: parser.TreeGenerator Class Reference
parser.TreeGenerator Class Reference
Public Member Functions
CommandTreeNode createCommands (String input, String language)
void recurse (CommandTreeNode root)
void printTestStatements (String value, String type, String name)
List< String > getMethodsList ()
void incrementIndex ()
int getIndex ()
void incrementListStartIndex ()
void incrementListEndIndex ()
Private Member Functions
Map< Pattern, Cases > createHandlerMap ()
Private Attributes
Map< Pattern, Cases > handlerMap
List< String > myInput
int index
CommandCase CommandCase
int ListStartCount = 0
int ListEndCount = 0
Detailed Description
Generates the command tree with the first command as the root
Author
Kei Yoshikoshi
Definition at line 21 of file TreeGenerator.java.
Member Function Documentation
CommandTreeNode parser.TreeGenerator.createCommands (String input, String language)
Create a CommandTreeNode that includes all the commands
Parameters
input : List of strings taken from the parser
Returns
: CommandTreeNode with commands
Definition at line 37 of file TreeGenerator.java.
References parser.TreeGenerator.createHandlerMap(), parser.CommandTreeNode.getName(), parser.CommandCase.getRoot(), and parser.CommandCase.initialize().
Referenced by controller.Controller.parseCommand().
Map<Pattern, Cases> parser.TreeGenerator.createHandlerMap () private
A method creates a map that maps regex patterns to a case class
Returns
Definition at line 90 of file TreeGenerator.java.
References parser.TreeGenerator.CommandCase, and util.PatternMapper.makePatterns().
Referenced by parser.TreeGenerator.createCommands().
int parser.TreeGenerator.getIndex ()
Implements parser.TreeWrapper.
Definition at line 130 of file TreeGenerator.java.
References parser.TreeGenerator.index.
List<String> parser.TreeGenerator.getMethodsList ()
Definition at line 122 of file TreeGenerator.java.
References parser.CommandCase.getMethodsList().
Referenced by controller.Controller.parseCommand().
void parser.TreeGenerator.incrementIndex ()
Implements parser.TreeWrapper.
Definition at line 126 of file TreeGenerator.java.
void parser.TreeGenerator.incrementListEndIndex ()
Implements parser.TreeWrapper.
Definition at line 138 of file TreeGenerator.java.
void parser.TreeGenerator.incrementListStartIndex ()
Implements parser.TreeWrapper.
Definition at line 134 of file TreeGenerator.java.
void parser.TreeGenerator.printTestStatements (String value, String type, String name)
A temporary method to print statements to visualize the tree.
Implements parser.TreeWrapper.
Definition at line 78 of file TreeGenerator.java.
void parser.TreeGenerator.recurse (CommandTreeNode root)
recurse method that generates the tree
Parameters
root
Implements parser.TreeWrapper.
Definition at line 62 of file TreeGenerator.java.
References parser.Cases.recurse().
Member Data Documentation
CommandCase parser.TreeGenerator.CommandCase private
Definition at line 25 of file TreeGenerator.java.
Referenced by parser.TreeGenerator.createHandlerMap().
Map<Pattern, Cases> parser.TreeGenerator.handlerMap private
Definition at line 22 of file TreeGenerator.java.
int parser.TreeGenerator.index private
Definition at line 24 of file TreeGenerator.java.
Referenced by parser.TreeGenerator.getIndex().
int parser.TreeGenerator.ListEndCount = 0 private
Definition at line 28 of file TreeGenerator.java.
int parser.TreeGenerator.ListStartCount = 0 private
Definition at line 27 of file TreeGenerator.java.
List<String> parser.TreeGenerator.myInput private
Definition at line 23 of file TreeGenerator.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/parser/TreeGenerator.java