slogo_team06: model.Variable Class Reference
model.Variable Class Reference
Public Member Functions
Variable (String var, Double num)
Double getValue ()
String getName ()
void setValue (Double val)
DoubleProperty valueProperty ()
StringProperty nameProperty ()
String toString ()
Private Attributes
DoubleProperty value
StringProperty name
Detailed Description
container class for user defined variables
Definition at line 13 of file Variable.java.
Constructor & Destructor Documentation
model.Variable.Variable (String var, Double num)
Definition at line 17 of file Variable.java.
Member Function Documentation
String model.Variable.getName ()
Definition at line 26 of file Variable.java.
Referenced by command.control.DoTimesCommand.calculateValue(), command.control.ForCommand.calculateValue(), and model.Variable.toString().
Double model.Variable.getValue ()
Definition at line 22 of file Variable.java.
Referenced by command.control.MakeVariableCommand.calculateValue(), command.control.DoTimesCommand.calculateValue(), command.control.ForCommand.calculateValue(), and model.Variable.toString().
StringProperty model.Variable.nameProperty ()
Definition at line 40 of file Variable.java.
References model.Variable.name.
void model.Variable.setValue (Double val)
Definition at line 30 of file Variable.java.
Referenced by command.control.MakeVariableCommand.calculateValue().
String model.Variable.toString ()
Definition at line 46 of file Variable.java.
References model.Variable.getName(), and model.Variable.getValue().
DoubleProperty model.Variable.valueProperty ()
Definition at line 34 of file Variable.java.
References model.Variable.value.
Member Data Documentation
StringProperty model.Variable.name private
Definition at line 15 of file Variable.java.
Referenced by model.Variable.nameProperty().
DoubleProperty model.Variable.value private
Definition at line 14 of file Variable.java.
Referenced by model.Variable.valueProperty().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/model/Variable.java