slogo_team06: ui.elements.IOElement Class Reference
ui.elements.IOElement Class Reference
Public Member Functions
IOElement (ResourceBundle resourceBundleIn, GUI myGui)
Node getBaseNode ()
TextField getInputField ()
Text getOutputField ()
Button getButton ()
Private Member Functions
void init (GUI myGui)
Private Attributes
VBox myNode
TextField inputField
Text outputField
Button confirmInput
ResourceBundle myResources
Detailed Description
Definition at line 13 of file IOElement.java.
Constructor & Destructor Documentation
ui.elements.IOElement.IOElement (ResourceBundle resourceBundleIn, GUI myGui)
Definition at line 21 of file IOElement.java.
References ui.elements.IOElement.init().
Member Function Documentation
Node ui.elements.IOElement.getBaseNode ()
Definition at line 41 of file IOElement.java.
References ui.elements.IOElement.myNode.
Referenced by ui.GUI.initialize().
Button ui.elements.IOElement.getButton ()
Definition at line 53 of file IOElement.java.
References ui.elements.IOElement.confirmInput.
Referenced by ui.elements.MenuBarElement.checkLanguageMenuItems().
TextField ui.elements.IOElement.getInputField ()
Definition at line 45 of file IOElement.java.
References ui.elements.IOElement.inputField.
Referenced by ui.elements.MenuBarElement.checkLanguageMenuItems(), ui.GUI.parseCommand(), and ui.GUI.setInputText().
Text ui.elements.IOElement.getOutputField ()
Definition at line 49 of file IOElement.java.
References ui.elements.IOElement.outputField.
Referenced by ui.GUI.setOutputText().
void ui.elements.IOElement.init (GUI myGui) private
Definition at line 26 of file IOElement.java.
References util.ButtonMaker.makeButton(), and ui.GUI.parseCommand().
Referenced by ui.elements.IOElement.IOElement().
Member Data Documentation
Button ui.elements.IOElement.confirmInput private
Definition at line 18 of file IOElement.java.
Referenced by ui.elements.IOElement.getButton().
TextField ui.elements.IOElement.inputField private
Definition at line 16 of file IOElement.java.
Referenced by ui.elements.IOElement.getInputField().
VBox ui.elements.IOElement.myNode private
Definition at line 14 of file IOElement.java.
Referenced by ui.elements.IOElement.getBaseNode().
ResourceBundle ui.elements.IOElement.myResources private
Definition at line 19 of file IOElement.java.
Text ui.elements.IOElement.outputField private
Definition at line 17 of file IOElement.java.
Referenced by ui.elements.IOElement.getOutputField().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/ui/elements/IOElement.java