slogo_team06: parser.CommandCase Class Reference
parser.CommandCase Class Reference
Public Member Functions
CommandCase (TreeWrapper wrapper, List< String > input)
void initialize (String language)
void recurse (CommandTreeNode root)
CommandTreeNode getRoot ()
List< String > getMethodsList ()
Private Member Functions
void makingInstructionsCase (CommandTreeNode root, String value)
String useResourceBundle (String input)
HashMap< String, String[]> createParametersMap ()
int obtainNumParams (String key)
String obtainSubCommand (String key)
Private Attributes
Map< String, String[]> parametersMap
boolean makingUserInstruction
List< String > methodList
List< Entry< String, Pattern > > languagePatternList
TreeWrapper wrapper
List< String > myInput
CommandTreeNode myRoot
Static Private Attributes
static final int PARAM_INDEX = 0
static final int TYPE_INDEX = 1
Detailed Description
A class that deals with when the word is a command.
Author
Kei Yoshikoshi
Definition at line 21 of file CommandCase.java.
Constructor & Destructor Documentation
parser.CommandCase.CommandCase (TreeWrapper wrapper, List< String > input)
Definition at line 33 of file CommandCase.java.
References parser.CommandCase.createParametersMap(), and parser.CommandCase.wrapper.
Member Function Documentation
HashMap<String, String[]> parser.CommandCase.createParametersMap () private
Creates a map that maps the Key to the number of parameters and its subcommand type
Returns
Definition at line 126 of file CommandCase.java.
Referenced by parser.CommandCase.CommandCase().
List<String> parser.CommandCase.getMethodsList ()
Definition at line 168 of file CommandCase.java.
References parser.CommandCase.methodList.
Referenced by parser.TreeGenerator.getMethodsList().
CommandTreeNode parser.CommandCase.getRoot ()
Definition at line 164 of file CommandCase.java.
References parser.CommandCase.myRoot.
Referenced by parser.TreeGenerator.createCommands().
void parser.CommandCase.initialize (String language)
Method used to initialize the tree generation
Parameters
language
Definition at line 45 of file CommandCase.java.
References parser.TreeWrapper.getIndex(), parser.TreeWrapper.incrementIndex(), util.PatternMapper.makePatterns(), parser.CommandCase.obtainNumParams(), parser.CommandCase.obtainSubCommand(), parser.TreeWrapper.printTestStatements(), parser.TreeWrapper.recurse(), and parser.CommandCase.useResourceBundle().
Referenced by parser.TreeGenerator.createCommands().
void parser.CommandCase.makingInstructionsCase (CommandTreeNode root, String value) private
recursive case when the command is to make an instruction
Parameters
root
value
Definition at line 91 of file CommandCase.java.
References parser.CommandTreeNode.add(), parser.CommandTreeNode.getName(), parser.CommandTreeNode.getType(), parser.CommandCase.obtainSubCommand(), parser.TreeWrapper.printTestStatements(), and parser.TreeWrapper.recurse().
Referenced by parser.CommandCase.recurse().
int parser.CommandCase.obtainNumParams (String key) private
Obtains the number of parameters given the key
Parameters
key
Returns
Definition at line 145 of file CommandCase.java.
References parser.CommandCase.PARAM_INDEX.
Referenced by parser.CommandCase.initialize(), and parser.CommandCase.recurse().
String parser.CommandCase.obtainSubCommand (String key) private
Obtains the subcommand type given the key
Parameters
key
Returns
Definition at line 155 of file CommandCase.java.
References parser.CommandCase.TYPE_INDEX.
Referenced by parser.CommandCase.initialize(), parser.CommandCase.makingInstructionsCase(), and parser.CommandCase.recurse().
void parser.CommandCase.recurse (CommandTreeNode root)
recursive method to generate the tree
Parameters
root
Implements parser.Cases.
Definition at line 64 of file CommandCase.java.
References parser.CommandTreeNode.add(), parser.TreeWrapper.getIndex(), parser.CommandTreeNode.getName(), parser.CommandTreeNode.getType(), parser.TreeWrapper.incrementIndex(), parser.CommandCase.makingInstructionsCase(), parser.CommandCase.obtainNumParams(), parser.CommandCase.obtainSubCommand(), parser.TreeWrapper.printTestStatements(), parser.TreeWrapper.recurse(), and parser.CommandCase.useResourceBundle().
String parser.CommandCase.useResourceBundle (String input) private
Looks up whether the command is in the resource bundle and throws an exception if not
Parameters
input
Returns
Definition at line 106 of file CommandCase.java.
Referenced by parser.CommandCase.initialize(), and parser.CommandCase.recurse().
Member Data Documentation
List<Entry<String, Pattern> > parser.CommandCase.languagePatternList private
Definition at line 28 of file CommandCase.java.
boolean parser.CommandCase.makingUserInstruction private
Definition at line 25 of file CommandCase.java.
List<String> parser.CommandCase.methodList private
Definition at line 26 of file CommandCase.java.
Referenced by parser.CommandCase.getMethodsList().
List<String> parser.CommandCase.myInput private
Definition at line 30 of file CommandCase.java.
CommandTreeNode parser.CommandCase.myRoot private
Definition at line 31 of file CommandCase.java.
Referenced by parser.CommandCase.getRoot().
final int parser.CommandCase.PARAM_INDEX = 0 static private
Definition at line 23 of file CommandCase.java.
Referenced by parser.CommandCase.obtainNumParams().
Map<String, String[]> parser.CommandCase.parametersMap private
Definition at line 22 of file CommandCase.java.
final int parser.CommandCase.TYPE_INDEX = 1 static private
Definition at line 24 of file CommandCase.java.
Referenced by parser.CommandCase.obtainSubCommand().
TreeWrapper parser.CommandCase.wrapper private
Definition at line 29 of file CommandCase.java.
Referenced by parser.CommandCase.CommandCase().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/parser/CommandCase.java