slogo_team06: parser.ConstantCase Class Reference
parser.ConstantCase Class Reference
Public Member Functions
ConstantCase (TreeWrapper wrapper, List< String > input)
void recurse (CommandTreeNode root)
Private Attributes
TreeWrapper wrapper
List< String > myInput
Detailed Description
A class that deals with when the word is a constant.
Author
Kei Yoshikoshi
Definition at line 11 of file ConstantCase.java.
Constructor & Destructor Documentation
parser.ConstantCase.ConstantCase (TreeWrapper wrapper, List< String > input)
Definition at line 15 of file ConstantCase.java.
References parser.ConstantCase.wrapper.
Member Function Documentation
void parser.ConstantCase.recurse (CommandTreeNode root)
recursive method to generate the Tree
Parameters
root
Implements parser.Cases.
Definition at line 25 of file ConstantCase.java.
References parser.CommandTreeNode.add(), parser.TreeWrapper.getIndex(), parser.CommandTreeNode.getName(), parser.CommandTreeNode.getType(), parser.TreeWrapper.incrementIndex(), and parser.TreeWrapper.printTestStatements().
Member Data Documentation
List<String> parser.ConstantCase.myInput private
Definition at line 13 of file ConstantCase.java.
TreeWrapper parser.ConstantCase.wrapper private
Definition at line 12 of file ConstantCase.java.
Referenced by parser.ConstantCase.ConstantCase().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/parser/ConstantCase.java