slogo_team06: errors.SLogoException Class Reference
errors.SLogoException Class Reference abstract
Public Member Functions
Throwable fillInStackTrace ()
Protected Member Functions
SLogoException (String format)
void popup (String message)
Private Attributes
Stage popupStage
Static Private Attributes
static final long serialVersionUID = 1L
static final int X_COOR = 300
static final int Y_COOR = 200
Detailed Description
Super class for all Exceptions thrown in this SLogo program
Author
Kei Yoshikoshi
Definition at line 17 of file SLogoException.java.
Constructor & Destructor Documentation
errors.SLogoException.SLogoException (String format) protected
Definition at line 23 of file SLogoException.java.
References errors.SLogoException.fillInStackTrace(), and errors.SLogoException.popup().
Member Function Documentation
Throwable errors.SLogoException.fillInStackTrace ()
disables stack trace
Definition at line 34 of file SLogoException.java.
Referenced by errors.SLogoException.SLogoException().
void errors.SLogoException.popup (String message) protected
A way for the program to display some error message
Parameters
message
Definition at line 43 of file SLogoException.java.
Referenced by errors.SLogoException.SLogoException().
Member Data Documentation
Stage errors.SLogoException.popupStage private
Definition at line 21 of file SLogoException.java.
final long errors.SLogoException.serialVersionUID = 1L static private
Definition at line 18 of file SLogoException.java.
final int errors.SLogoException.X_COOR = 300 static private
Definition at line 19 of file SLogoException.java.
final int errors.SLogoException.Y_COOR = 200 static private
Definition at line 20 of file SLogoException.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/errors/SLogoException.java