slogo_team06: ui.elements.MenuBarElement Class Reference
ui.elements.MenuBarElement Class Reference
Public Member Functions
MenuBarElement (ResourceBundle resourcesIn, CanvasElement canvasPaneIn, IOElement ioPaneIn, Color backgroundColor, String[] languagesIn, String defaultLanguageIn, Pen penIn, GUI myGuiIn)
String getSelectedLanguage ()
Node getBaseNode ()
Private Member Functions
void init (Color backgroundColor)
Node makeMenuBar ()
ColorPicker makeColorPicker (Color defaultColor, EventHandler< ActionEvent > handler)
void changeBackgroundColor ()
void changePenColor ()
Menu makeMenu (String name, String[] list)
void checkLanguageMenuItems (String language, boolean selected, Menu menu)
void toggleMenuItems (Menu menu, String input, boolean state)
void showHTMLHelp ()
Private Attributes
final String helpPageURL
ToolBar tb
ResourceBundle myResources
CanvasElement canvasPane
IOElement ioPane
SVGPath svg
ColorPicker backgroundColorPicker
ColorPicker penColorPicker
Pen myPen
String languages []
String selectedLanguage
GUI myGui
Detailed Description
Definition at line 18 of file MenuBarElement.java.
Constructor & Destructor Documentation
ui.elements.MenuBarElement.MenuBarElement (ResourceBundle resourcesIn, CanvasElement canvasPaneIn, IOElement ioPaneIn, Color backgroundColor, String[] languagesIn, String defaultLanguageIn, Pen penIn, GUI myGuiIn)
Definition at line 33 of file MenuBarElement.java.
References ui.elements.MenuBarElement.init().
Member Function Documentation
void ui.elements.MenuBarElement.changeBackgroundColor () private
Handler for the background color picker
Definition at line 113 of file MenuBarElement.java.
References ui.elements.CanvasElement.setBackground().
Referenced by ui.elements.MenuBarElement.init().
void ui.elements.MenuBarElement.changePenColor () private
Handler for the pen color picker
Definition at line 123 of file MenuBarElement.java.
References ui.Pen.setColor().
Referenced by ui.elements.MenuBarElement.init().
void ui.elements.MenuBarElement.checkLanguageMenuItems (String language, boolean selected, Menu menu) private
Checks a single menu item within a given menu
Parameters
language
selected
menu
Definition at line 151 of file MenuBarElement.java.
References ui.elements.IOElement.getButton(), ui.elements.IOElement.getInputField(), and ui.elements.MenuBarElement.toggleMenuItems().
Referenced by ui.elements.MenuBarElement.makeMenu().
Node ui.elements.MenuBarElement.getBaseNode ()
Definition at line 197 of file MenuBarElement.java.
References ui.elements.MenuBarElement.tb.
Referenced by ui.GUI.initialize().
String ui.elements.MenuBarElement.getSelectedLanguage ()
Definition at line 193 of file MenuBarElement.java.
References ui.elements.MenuBarElement.selectedLanguage.
Referenced by ui.GUI.parseCommand().
void ui.elements.MenuBarElement.init (Color backgroundColor) private
Definition at line 48 of file MenuBarElement.java.
References ui.elements.MenuBarElement.changeBackgroundColor(), ui.elements.MenuBarElement.changePenColor(), ui.Pen.getColor(), ui.elements.MenuBarElement.makeColorPicker(), and ui.elements.MenuBarElement.makeMenuBar().
Referenced by ui.elements.MenuBarElement.MenuBarElement().
ColorPicker ui.elements.MenuBarElement.makeColorPicker (Color defaultColor, EventHandler< ActionEvent > handler) private
Makes a color picker with the given default color and handler
Parameters
defaultColor
handler
Returns
Definition at line 94 of file MenuBarElement.java.
Referenced by ui.elements.MenuBarElement.init().
Menu ui.elements.MenuBarElement.makeMenu (String name, String[] list) private
Creates Menu - temporary method before inheritance hierarchy
Definition at line 130 of file MenuBarElement.java.
References ui.elements.MenuBarElement.checkLanguageMenuItems().
Referenced by ui.elements.MenuBarElement.makeMenuBar().
Node ui.elements.MenuBarElement.makeMenuBar () private
Creates the top menu bar
Returns
Definition at line 66 of file MenuBarElement.java.
References ui.GUI.createNewWorkspace(), ui.elements.MenuBarElement.makeMenu(), and ui.elements.MenuBarElement.showHTMLHelp().
Referenced by ui.elements.MenuBarElement.init().
void ui.elements.MenuBarElement.showHTMLHelp () private
Shows the HTML Help window
Definition at line 188 of file MenuBarElement.java.
References util.HTMLHelpPage.show().
Referenced by ui.elements.MenuBarElement.makeMenuBar().
void ui.elements.MenuBarElement.toggleMenuItems (Menu menu, String input, boolean state) private
Toggles a menuItem
Parameters
menu
input
state
Definition at line 176 of file MenuBarElement.java.
Referenced by ui.elements.MenuBarElement.checkLanguageMenuItems().
Member Data Documentation
ColorPicker ui.elements.MenuBarElement.backgroundColorPicker private
Definition at line 26 of file MenuBarElement.java.
CanvasElement ui.elements.MenuBarElement.canvasPane private
Definition at line 23 of file MenuBarElement.java.
final String ui.elements.MenuBarElement.helpPageURL private
Initial value:
=
            "http://www.cs.duke.edu/courses/compsci308/spring15/assign/03_slogo/commands.php"
Definition at line 19 of file MenuBarElement.java.
IOElement ui.elements.MenuBarElement.ioPane private
Definition at line 24 of file MenuBarElement.java.
String ui.elements.MenuBarElement.languages[] private
Definition at line 29 of file MenuBarElement.java.
GUI ui.elements.MenuBarElement.myGui private
Definition at line 31 of file MenuBarElement.java.
Pen ui.elements.MenuBarElement.myPen private
Definition at line 28 of file MenuBarElement.java.
ResourceBundle ui.elements.MenuBarElement.myResources private
Definition at line 22 of file MenuBarElement.java.
ColorPicker ui.elements.MenuBarElement.penColorPicker private
Definition at line 27 of file MenuBarElement.java.
String ui.elements.MenuBarElement.selectedLanguage private
Definition at line 30 of file MenuBarElement.java.
Referenced by ui.elements.MenuBarElement.getSelectedLanguage().
SVGPath ui.elements.MenuBarElement.svg private
Definition at line 25 of file MenuBarElement.java.
ToolBar ui.elements.MenuBarElement.tb private
Definition at line 21 of file MenuBarElement.java.
Referenced by ui.elements.MenuBarElement.getBaseNode().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/ui/elements/MenuBarElement.java