slogo_team06: model.TreeInterpreter Class Reference
model.TreeInterpreter Class Reference
Public Member Functions
TreeInterpreter ()
void interpretTree (CommandTreeNode node)
Constructor[] getConstructors (Class<?> className)
void executeCommand (CommandTreeNode node, List< Object > paramList)
void update (CommandTreeNode node, List< Object > paramList)
List< Turtle > getTurtleList ()
VariableList getVariableList ()
double getActiveTurtleIndex ()
void setActiveTurtleIndex (int index)
Map< String, List< CommandTreeNode > > getUserCommands ()
void setUserCommands (Map< String, List< CommandTreeNode >> commands)
Private Attributes
CommandFactory factory
VariableList variables
int activeTurtleIndex
List< Turtle > listTurtles
Map< String, List< CommandTreeNode > > userCommands
Detailed Description
Main "MODEL" Class that traverses through one command tree, interprets each subcommand, and updates back-end elements (turtles, variableList, etc.) accordingly
Author
OWNER
Definition at line 21 of file TreeInterpreter.java.
Constructor & Destructor Documentation
model.TreeInterpreter.TreeInterpreter ()
Definition at line 28 of file TreeInterpreter.java.
Member Function Documentation
void model.TreeInterpreter.executeCommand (CommandTreeNode node, List< Object > paramList)
Creates a command using reflection, invokes calculateValue method in command class with the parameter values
Parameters
node,contains information as to which command is created
paramList,list of parameter values needed for one command
Definition at line 64 of file TreeInterpreter.java.
References model.CommandFactory.createCommand(), model.TreeInterpreter.getConstructors(), parser.CommandTreeNode.getName(), parser.CommandTreeNode.getType(), and parser.CommandTreeNode.setValue().
Referenced by model.TreeInterpreter.update().
double model.TreeInterpreter.getActiveTurtleIndex ()
Definition at line 132 of file TreeInterpreter.java.
References model.TreeInterpreter.activeTurtleIndex.
Referenced by command.control.IDCommand.calculateValue().
Constructor [] model.TreeInterpreter.getConstructors (Class<?> className)
Definition at line 55 of file TreeInterpreter.java.
Referenced by model.TreeInterpreter.executeCommand().
List<Turtle> model.TreeInterpreter.getTurtleList ()
Definition at line 123 of file TreeInterpreter.java.
References model.TreeInterpreter.listTurtles.
Referenced by command.control.TurtlesCommand.calculateValue(), command.control.AskWithCommand.calculateValue(), command.control.TellCommand.calculateValue(), and controller.Controller.createTurtle().
Map<String, List<CommandTreeNode> > model.TreeInterpreter.getUserCommands ()
Definition at line 140 of file TreeInterpreter.java.
References model.TreeInterpreter.userCommands.
Referenced by command.control.ExecuteUserCommand.calculateValue(), and command.control.MakeUserInstructionCommand.calculateValue().
VariableList model.TreeInterpreter.getVariableList ()
Definition at line 127 of file TreeInterpreter.java.
References model.TreeInterpreter.variables.
Referenced by command.control.DoTimesCommand.calculateValue(), command.control.ForCommand.calculateValue(), and command.control.MakeVariableCommand.MakeVariableCommand().
void model.TreeInterpreter.interpretTree (CommandTreeNode node)
Recursive method that traverses through the command tree starting from parent node
Parameters
node
Definition at line 40 of file TreeInterpreter.java.
References parser.CommandTreeNode.getChildren(), parser.CommandTreeNode.getType(), and model.TreeInterpreter.update().
Referenced by command.control.AskWithCommand.calculateValue(), command.control.ExecuteUserCommand.calculateValue(), command.control.AskCommand.calculateValue(), command.control.RepeatCommand.calculateValue(), command.control.IfCommand.calculateValue(), command.control.DoTimesCommand.calculateValue(), command.control.ForCommand.calculateValue(), command.control.IfElseCommand.calculateValue(), and controller.Controller.parseCommand().
void model.TreeInterpreter.setActiveTurtleIndex (int index)
Definition at line 136 of file TreeInterpreter.java.
Referenced by command.control.AskWithCommand.calculateValue(), command.control.TellCommand.calculateValue(), and command.control.AskCommand.calculateValue().
void model.TreeInterpreter.setUserCommands (Map< String, List< CommandTreeNode >> commands)
Definition at line 144 of file TreeInterpreter.java.
Referenced by command.control.MakeUserInstructionCommand.calculateValue().
void model.TreeInterpreter.update (CommandTreeNode node, List< Object > paramList)
Calls executeCommand if the node represents Command, adding appropriate elements to paramList accordingly
Parameters
current node
paramList,list of parameters values needed for one command
Definition at line 98 of file TreeInterpreter.java.
References model.TreeInterpreter.executeCommand(), model.VariableList.get(), parser.CommandTreeNode.getName(), parser.CommandTreeNode.getType(), and parser.CommandTreeNode.setValue().
Referenced by model.TreeInterpreter.interpretTree().
Member Data Documentation
int model.TreeInterpreter.activeTurtleIndex private
Definition at line 24 of file TreeInterpreter.java.
Referenced by model.TreeInterpreter.getActiveTurtleIndex().
CommandFactory model.TreeInterpreter.factory private
Definition at line 22 of file TreeInterpreter.java.
List<Turtle> model.TreeInterpreter.listTurtles private
Definition at line 25 of file TreeInterpreter.java.
Referenced by model.TreeInterpreter.getTurtleList().
Map<String, List<CommandTreeNode> > model.TreeInterpreter.userCommands private
Definition at line 26 of file TreeInterpreter.java.
Referenced by model.TreeInterpreter.getUserCommands().
VariableList model.TreeInterpreter.variables private
Definition at line 23 of file TreeInterpreter.java.
Referenced by model.TreeInterpreter.getVariableList().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/model/TreeInterpreter.java