slogo_team06: command.control.MakeUserInstructionCommand Class Reference
command.control.MakeUserInstructionCommand Class Reference
Public Member Functions
MakeUserInstructionCommand (CommandTreeNode node1, CommandTreeNode node2, CommandTreeNode node3, TreeInterpreter t)
double calculateValue ()
Private Attributes
String commandName
CommandTreeNode parameters
CommandTreeNode subCommands
TreeInterpreter tree
Detailed Description
STILL A WORKING PROGRESS
Author
OWNER
Definition at line 14 of file MakeUserInstructionCommand.java.
Constructor & Destructor Documentation
command.control.MakeUserInstructionCommand.MakeUserInstructionCommand (CommandTreeNode node1, CommandTreeNode node2, CommandTreeNode node3, TreeInterpreter t)
Definition at line 20 of file MakeUserInstructionCommand.java.
References parser.CommandTreeNode.getName().
Member Function Documentation
double command.control.MakeUserInstructionCommand.calculateValue ()
Definition at line 30 of file MakeUserInstructionCommand.java.
References model.TreeInterpreter.getUserCommands(), and model.TreeInterpreter.setUserCommands().
Member Data Documentation
String command.control.MakeUserInstructionCommand.commandName private
Definition at line 15 of file MakeUserInstructionCommand.java.
CommandTreeNode command.control.MakeUserInstructionCommand.parameters private
Definition at line 16 of file MakeUserInstructionCommand.java.
CommandTreeNode command.control.MakeUserInstructionCommand.subCommands private
Definition at line 17 of file MakeUserInstructionCommand.java.
TreeInterpreter command.control.MakeUserInstructionCommand.tree private
Definition at line 18 of file MakeUserInstructionCommand.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/command/control/MakeUserInstructionCommand.java