slogo_team06: ui.elements.TPropertiesElement Class Reference
ui.elements.TPropertiesElement Class Reference
Public Member Functions
TPropertiesElement (final ResourceBundle resourcesIn, TurtleView tViewIn, Pen penIn, Stage stageIn, GUI guiIn)
Node getMyBaseNode ()
Private Member Functions
void init ()
HBox makeTurtleHeadingBox ()
void selectAndChangeTurtleImage ()
Private Attributes
VBox myBaseNode
ResourceBundle myResources
TurtleView tView
Pen myPen
Stage myStage
GUI myGui
Detailed Description
Definition at line 23 of file TPropertiesElement.java.
Constructor & Destructor Documentation
ui.elements.TPropertiesElement.TPropertiesElement (final ResourceBundle resourcesIn, TurtleView tViewIn, Pen penIn, Stage stageIn, GUI guiIn)
Definition at line 32 of file TPropertiesElement.java.
References ui.elements.TPropertiesElement.init().
Member Function Documentation
Node ui.elements.TPropertiesElement.getMyBaseNode ()
Definition at line 119 of file TPropertiesElement.java.
References ui.elements.TPropertiesElement.myBaseNode.
Referenced by ui.GUI.initialize().
void ui.elements.TPropertiesElement.init () private
Definition at line 42 of file TPropertiesElement.java.
References ui.GUI.DEFAULT_TURTLE_IMAGE_PATH, util.ButtonMaker.makeButton(), util.ButtonMaker.makeToggleButton(), ui.elements.TPropertiesElement.makeTurtleHeadingBox(), ui.GUI.makeTurtleView(), ui.elements.TPropertiesElement.selectAndChangeTurtleImage(), ui.Pen.setLineStyle(), ui.Pen.setPenIsDown(), and ui.TurtleView.setTurtleVisible().
Referenced by ui.elements.TPropertiesElement.TPropertiesElement().
HBox ui.elements.TPropertiesElement.makeTurtleHeadingBox () private
Definition at line 80 of file TPropertiesElement.java.
References ui.TurtleView.getHeading().
Referenced by ui.elements.TPropertiesElement.init().
void ui.elements.TPropertiesElement.selectAndChangeTurtleImage () private
Shows a filechooser to select a new turtle image, then changes to that image
Definition at line 103 of file TPropertiesElement.java.
References ui.TurtleView.setImage().
Referenced by ui.elements.TPropertiesElement.init().
Member Data Documentation
VBox ui.elements.TPropertiesElement.myBaseNode private
Definition at line 25 of file TPropertiesElement.java.
Referenced by ui.elements.TPropertiesElement.getMyBaseNode().
GUI ui.elements.TPropertiesElement.myGui private
Definition at line 30 of file TPropertiesElement.java.
Pen ui.elements.TPropertiesElement.myPen private
Definition at line 28 of file TPropertiesElement.java.
ResourceBundle ui.elements.TPropertiesElement.myResources private
Definition at line 26 of file TPropertiesElement.java.
Stage ui.elements.TPropertiesElement.myStage private
Definition at line 29 of file TPropertiesElement.java.
TurtleView ui.elements.TPropertiesElement.tView private
Definition at line 27 of file TPropertiesElement.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/ui/elements/TPropertiesElement.java