slogo_team06: ui.Pen Class Reference
ui.Pen Class Reference
Public Member Functions
Pen (Canvas canvasIn, Color startingColor, boolean penIsDownIn)
Pair< Double, Double > draw (double x1, double y1, double x2, double y2, boolean hasTurtle)
void setPenIsDown (boolean penIsDownIn)
Color getColor ()
void setColor (Color color)
void setLineStyle (String ls)
Private Attributes
Color myColor
boolean penIsDown
Canvas myCanvas
double canvasCenterX
double canvasCenterY
LineDrawHelper artists []
LineDrawHelper myArtist
Detailed Description
Definition at line 12 of file Pen.java.
Constructor & Destructor Documentation
ui.Pen.Pen (Canvas canvasIn, Color startingColor, boolean penIsDownIn)
Definition at line 22 of file Pen.java.
Member Function Documentation
Pair<Double, Double> ui.Pen.draw (double x1, double y1, double x2, double y2, boolean hasTurtle)
Definition at line 31 of file Pen.java.
References ui.artists.LineDrawHelper.drawLine().
Referenced by ui.TurtleView.draw().
Color ui.Pen.getColor ()
Definition at line 46 of file Pen.java.
References ui.Pen.myColor.
Referenced by ui.elements.MenuBarElement.init().
void ui.Pen.setColor (Color color)
Definition at line 50 of file Pen.java.
Referenced by ui.elements.MenuBarElement.changePenColor().
void ui.Pen.setLineStyle (String ls)
Definition at line 54 of file Pen.java.
Referenced by ui.elements.TPropertiesElement.init().
void ui.Pen.setPenIsDown (boolean penIsDownIn)
Definition at line 42 of file Pen.java.
Referenced by ui.elements.TPropertiesElement.init().
Member Data Documentation
LineDrawHelper ui.Pen.artists[] private
Initial value:
= { new NormalLineDrawHelper(), new DashedLineDrawHelper(),
                                        new DottedLineDrawHelper() }
Definition at line 18 of file Pen.java.
double ui.Pen.canvasCenterX private
Definition at line 16 of file Pen.java.
double ui.Pen.canvasCenterY private
Definition at line 17 of file Pen.java.
LineDrawHelper ui.Pen.myArtist private
Definition at line 20 of file Pen.java.
Canvas ui.Pen.myCanvas private
Definition at line 15 of file Pen.java.
Color ui.Pen.myColor private
Definition at line 13 of file Pen.java.
Referenced by ui.Pen.getColor().
boolean ui.Pen.penIsDown private
Definition at line 14 of file Pen.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/ui/Pen.java