slogo_team06: model.VariableList Class Reference
model.VariableList Class Reference
Public Member Functions
VariableList ()
void add (String name)
Variable get (String name)
boolean contains (String name)
void printThing ()
ObservableList< Variable > getList ()
Private Attributes
ObservableList< Variable > list
Detailed Description
: Make this more elegant...
Definition at line 13 of file VariableList.java.
Constructor & Destructor Documentation
model.VariableList.VariableList ()
Definition at line 16 of file VariableList.java.
Member Function Documentation
void model.VariableList.add (String name)
Definition at line 23 of file VariableList.java.
Referenced by command.control.MakeVariableCommand.calculateValue(), and model.VariableList.get().
boolean model.VariableList.contains (String name)
Definition at line 35 of file VariableList.java.
Referenced by command.control.MakeVariableCommand.calculateValue().
Variable model.VariableList.get (String name)
Definition at line 27 of file VariableList.java.
References model.VariableList.add().
Referenced by command.control.MakeVariableCommand.calculateValue(), command.control.DoTimesCommand.calculateValue(), command.control.ForCommand.calculateValue(), and model.TreeInterpreter.update().
ObservableList<Variable> model.VariableList.getList ()
Definition at line 48 of file VariableList.java.
References model.VariableList.list.
void model.VariableList.printThing ()
Definition at line 42 of file VariableList.java.
Member Data Documentation
ObservableList<Variable> model.VariableList.list private
Definition at line 14 of file VariableList.java.
Referenced by model.VariableList.getList().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/model/VariableList.java