slogo_team06: controller.Controller Class Reference
controller.Controller Class Reference
Public Member Functions
Controller (WorkspaceManager wm)
void init (Stage s)
void createTurtle (TurtleView view)
void parseCommand (String input, String language)
void addCommandHistory (String input)
Set< String > getPrevCommandList ()
void createNewWorkspace ()
Private Member Functions
void addCommandHistory (String name, CommandTreeNode prev)
Private Attributes
SceneUpdater sceneUpdater
Map< String, CommandTreeNode > previousCommands
TreeGenerator generator
TreeInterpreter interpreter
WorkspaceManager myManager
Detailed Description
Definition at line 16 of file Controller.java.
Constructor & Destructor Documentation
controller.Controller.Controller (WorkspaceManager wm)
Definition at line 23 of file Controller.java.
Member Function Documentation
void controller.Controller.addCommandHistory (String name, CommandTreeNode prev) private
Definition at line 59 of file Controller.java.
void controller.Controller.addCommandHistory (String input)
Definition at line 66 of file Controller.java.
References ui.SceneUpdater.addCommandHistory().
void controller.Controller.createNewWorkspace ()
Definition at line 74 of file Controller.java.
References main.WorkspaceManager.createWorkspace().
Referenced by ui.SceneUpdater.createNewWorkspace().
void controller.Controller.createTurtle (TurtleView view)
Definition at line 35 of file Controller.java.
References model.TreeInterpreter.getTurtleList().
Referenced by ui.SceneUpdater.createTurtle().
Set<String> controller.Controller.getPrevCommandList ()
Definition at line 70 of file Controller.java.
Referenced by ui.SceneUpdater.getPrevCommandList().
void controller.Controller.init (Stage s)
Definition at line 30 of file Controller.java.
References ui.SceneUpdater.initGUI().
Referenced by main.WorkspaceManager.createWorkspace().
void controller.Controller.parseCommand (String input, String language)
Parses command from front-end and sends the result to back-end
Parameters
input
language
Definition at line 48 of file Controller.java.
References ui.SceneUpdater.addCommandHistory(), parser.TreeGenerator.createCommands(), parser.TreeGenerator.getMethodsList(), parser.CommandTreeNode.getValue(), model.TreeInterpreter.interpretTree(), and ui.SceneUpdater.setOutputText().
Referenced by ui.SceneUpdater.sendCommands().
Member Data Documentation
TreeGenerator controller.Controller.generator private
Definition at line 19 of file Controller.java.
TreeInterpreter controller.Controller.interpreter private
Definition at line 20 of file Controller.java.
WorkspaceManager controller.Controller.myManager private
Definition at line 21 of file Controller.java.
Map<String, CommandTreeNode> controller.Controller.previousCommands private
Definition at line 18 of file Controller.java.
SceneUpdater controller.Controller.sceneUpdater private
Definition at line 17 of file Controller.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/controller/Controller.java