slogo_team06: ui.TableModel Class Reference
ui.TableModel Class Reference
Public Member Functions
int getColumnCount ()
int getRowCount ()
String getColumnName (int col)
Object getValueAt (int row, int col)
Class getColumnClass (int c)
boolean isCellEditable (int row, int col)
void setValueAt (Object value, int row, int col)
Private Member Functions
void printDebugData ()
Private Attributes
boolean DEBUG = false
String[] columnNames
Object[][] data
Detailed Description
Definition at line 3 of file TableModel.java.
Member Function Documentation
Class ui.TableModel.getColumnClass (int c)
Definition at line 39 of file TableModel.java.
References ui.TableModel.getValueAt().
int ui.TableModel.getColumnCount ()
Definition at line 18 of file TableModel.java.
Referenced by ui.TableModel.printDebugData().
String ui.TableModel.getColumnName (int col)
Definition at line 26 of file TableModel.java.
int ui.TableModel.getRowCount ()
Definition at line 22 of file TableModel.java.
Referenced by ui.TableModel.printDebugData().
Object ui.TableModel.getValueAt (int row, int col)
Definition at line 30 of file TableModel.java.
Referenced by ui.TableModel.getColumnClass().
boolean ui.TableModel.isCellEditable (int row, int col)
Definition at line 46 of file TableModel.java.
void ui.TableModel.printDebugData () private
Definition at line 75 of file TableModel.java.
References ui.TableModel.getColumnCount(), and ui.TableModel.getRowCount().
Referenced by ui.TableModel.setValueAt().
void ui.TableModel.setValueAt (Object value, int row, int col)
Definition at line 60 of file TableModel.java.
References ui.TableModel.printDebugData().
Member Data Documentation
String [] ui.TableModel.columnNames private
Initial value:
= { "First Name", "Last Name", "Sport",
                                    "# of Years", "Vegetarian" }
Definition at line 6 of file TableModel.java.
Object [][] ui.TableModel.data private
Initial value:
= {
                               { "Kathy", "Smith", "Snowboarding", new Integer(5),
                                new Boolean(false) },
                               { "John", "Doe", "Rowing", new Integer(3), new Boolean(true) },
                               { "Sue", "Black", "Knitting", new Integer(2), new Boolean(false) },
                               { "Jane", "White", "Speed reading", new Integer(20),
                                new Boolean(true) },
                               { "Joe", "Brown", "Pool", new Integer(10), new Boolean(false) } }
Definition at line 9 of file TableModel.java.
boolean ui.TableModel.DEBUG = false private
Definition at line 4 of file TableModel.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/ui/TableModel.java