slogo_team06: model.Turtle Class Reference
model.Turtle Class Reference
Public Member Functions
Turtle ()
void setHeading (double degrees)
void setLine (boolean tf)
void setTurtleVisibility (boolean tf)
void updateTurtleViewers ()
void setXY (double x, double y)
void setClear (boolean sc)
double getX ()
double getY ()
double getHeading ()
boolean getLine ()
boolean getVisibility ()
boolean getCleared ()
Private Attributes
double xLocation
double yLocation
boolean isDrawingLine
boolean isTurtleShowing
boolean isCleared
Color penColor
double heading
Detailed Description
Container for anything that draws on the canvas
Author
GA
Definition at line 13 of file Turtle.java.
Constructor & Destructor Documentation
model.Turtle.Turtle ()
Definition at line 22 of file Turtle.java.
Member Function Documentation
boolean model.Turtle.getCleared ()
Definition at line 80 of file Turtle.java.
References model.Turtle.isCleared.
Referenced by ui.TurtleView.update().
double model.Turtle.getHeading ()
Definition at line 68 of file Turtle.java.
References model.Turtle.heading.
Referenced by command.turtle.RightCommand.calculateValue(), command.turtle.HeadingCommand.calculateValue(), command.turtle.ForwardCommand.calculateValue(), command.turtle.LeftCommand.calculateValue(), command.turtle.BackwardCommand.calculateValue(), and ui.TurtleView.update().
boolean model.Turtle.getLine ()
Definition at line 72 of file Turtle.java.
References model.Turtle.isDrawingLine.
Referenced by command.turtle.IsPenDownCommand.calculateValue().
boolean model.Turtle.getVisibility ()
Definition at line 76 of file Turtle.java.
References model.Turtle.isTurtleShowing.
Referenced by command.turtle.IsShowingCommand.calculateValue(), and ui.TurtleView.update().
double model.Turtle.getX ()
Definition at line 60 of file Turtle.java.
References model.Turtle.xLocation.
Referenced by command.turtle.XCoordinateCommand.calculateValue(), command.turtle.HomeCommand.calculateValue(), command.turtle.ClearScreenCommand.calculateValue(), command.turtle.SetPositionCommand.calculateValue(), command.turtle.SetTowardsCommand.calculateValue(), command.turtle.ForwardCommand.calculateValue(), command.turtle.BackwardCommand.calculateValue(), and ui.TurtleView.update().
double model.Turtle.getY ()
Definition at line 64 of file Turtle.java.
References model.Turtle.yLocation.
Referenced by command.turtle.YCoordinateCommand.calculateValue(), command.turtle.HomeCommand.calculateValue(), command.turtle.ClearScreenCommand.calculateValue(), command.turtle.SetPositionCommand.calculateValue(), command.turtle.SetTowardsCommand.calculateValue(), command.turtle.ForwardCommand.calculateValue(), command.turtle.BackwardCommand.calculateValue(), and ui.TurtleView.update().
void model.Turtle.setClear (boolean sc)
Definition at line 56 of file Turtle.java.
Referenced by command.turtle.ClearScreenCommand.calculateValue().
void model.Turtle.setHeading (double degrees)
Definition at line 32 of file Turtle.java.
Referenced by command.turtle.ClearScreenCommand.calculateValue(), command.turtle.SetHeadingCommand.calculateValue(), command.turtle.RightCommand.calculateValue(), command.turtle.SetTowardsCommand.calculateValue(), and command.turtle.LeftCommand.calculateValue().
void model.Turtle.setLine (boolean tf)
Definition at line 37 of file Turtle.java.
Referenced by command.turtle.PenDownCommand.calculateValue(), and command.turtle.PenUpCommand.calculateValue().
void model.Turtle.setTurtleVisibility (boolean tf)
Definition at line 41 of file Turtle.java.
Referenced by command.turtle.ShowTurtleCommand.calculateValue(), and command.turtle.HideTurtleCommand.calculateValue().
void model.Turtle.setXY (double x, double y)
Definition at line 51 of file Turtle.java.
Referenced by command.turtle.HomeCommand.calculateValue(), command.turtle.ClearScreenCommand.calculateValue(), command.turtle.SetPositionCommand.calculateValue(), command.turtle.ForwardCommand.calculateValue(), and command.turtle.BackwardCommand.calculateValue().
void model.Turtle.updateTurtleViewers ()
Definition at line 46 of file Turtle.java.
Referenced by command.turtle.HomeCommand.calculateValue(), command.turtle.PenUpCommand.calculateValue(), command.turtle.PenDownCommand.calculateValue(), command.turtle.ShowTurtleCommand.calculateValue(), command.turtle.ClearScreenCommand.calculateValue(), command.turtle.RightCommand.calculateValue(), command.turtle.SetHeadingCommand.calculateValue(), command.turtle.HideTurtleCommand.calculateValue(), command.turtle.SetTowardsCommand.calculateValue(), command.turtle.SetPositionCommand.calculateValue(), command.turtle.ForwardCommand.calculateValue(), command.turtle.LeftCommand.calculateValue(), and command.turtle.BackwardCommand.calculateValue().
Member Data Documentation
double model.Turtle.heading private
Definition at line 20 of file Turtle.java.
Referenced by model.Turtle.getHeading().
boolean model.Turtle.isCleared private
Definition at line 18 of file Turtle.java.
Referenced by model.Turtle.getCleared().
boolean model.Turtle.isDrawingLine private
Definition at line 16 of file Turtle.java.
Referenced by model.Turtle.getLine().
boolean model.Turtle.isTurtleShowing private
Definition at line 17 of file Turtle.java.
Referenced by model.Turtle.getVisibility().
Color model.Turtle.penColor private
Definition at line 19 of file Turtle.java.
double model.Turtle.xLocation private
Definition at line 14 of file Turtle.java.
Referenced by model.Turtle.getX().
double model.Turtle.yLocation private
Definition at line 15 of file Turtle.java.
Referenced by model.Turtle.getY().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/model/Turtle.java