slogo_team06: ui.elements.CanvasElement Class Reference
ui.elements.CanvasElement Class Reference
Public Member Functions
CanvasElement (Color color, double width, double height)
Canvas getCanvas ()
StackPane getBaseNode ()
void setBackground (Background background)
Package Attributes
StackPane canvasHolder
Canvas canvas
Detailed Description
Definition at line 10 of file CanvasElement.java.
Constructor & Destructor Documentation
ui.elements.CanvasElement.CanvasElement (Color color, double width, double height)
Definition at line 14 of file CanvasElement.java.
Member Function Documentation
StackPane ui.elements.CanvasElement.getBaseNode ()
Definition at line 27 of file CanvasElement.java.
References ui.elements.CanvasElement.canvasHolder.
Referenced by ui.GUI.initialize(), and ui.GUI.makeTurtleView().
Canvas ui.elements.CanvasElement.getCanvas ()
Definition at line 23 of file CanvasElement.java.
References ui.elements.CanvasElement.canvas.
Referenced by ui.GUI.initialize(), and ui.GUI.makeTurtleView().
void ui.elements.CanvasElement.setBackground (Background background)
Definition at line 31 of file CanvasElement.java.
Referenced by ui.elements.MenuBarElement.changeBackgroundColor().
Member Data Documentation
Canvas ui.elements.CanvasElement.canvas package
Definition at line 12 of file CanvasElement.java.
Referenced by ui.elements.CanvasElement.getCanvas().
StackPane ui.elements.CanvasElement.canvasHolder package
Definition at line 11 of file CanvasElement.java.
Referenced by ui.elements.CanvasElement.getBaseNode().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/ui/elements/CanvasElement.java