slogo_team06: ui.elements.InfoElement Class Reference
ui.elements.InfoElement Class Reference
Public Member Functions
InfoElement (GUI gui)
void setBindVariableList (String command, double value)
void setBindCommandList (String command)
Node getBaseNode ()
List< TableView< TableElements > > getTables ()
Package Functions
private< T > TableView< TableElements > makeTable (List< String > columnNames)
Private Member Functions
void init ()
void update ()
Private Attributes
VBox myBaseNode
List< TableView< TableElements > > myTables
ObservableList< TableElements > var
ObservableList< TableElements > commands
TableView< TableElements > prevCommandsTable
TableView< TableElements > variablesTable
GUI myGUI
Detailed Description
Definition at line 20 of file InfoElement.java.
Constructor & Destructor Documentation
ui.elements.InfoElement.InfoElement (GUI gui)
Definition at line 31 of file InfoElement.java.
References ui.elements.InfoElement.init().
Member Function Documentation
Node ui.elements.InfoElement.getBaseNode ()
Definition at line 111 of file InfoElement.java.
References ui.elements.InfoElement.myBaseNode.
Referenced by ui.GUI.initialize(), and ui.GUI.makeTurtleView().
List<TableView<TableElements> > ui.elements.InfoElement.getTables ()
Definition at line 115 of file InfoElement.java.
References ui.elements.InfoElement.myTables.
Referenced by ui.GUI.bindTable().
void ui.elements.InfoElement.init () private
Definition at line 36 of file InfoElement.java.
References ui.elements.InfoElement.makeTable().
Referenced by ui.elements.InfoElement.InfoElement().
private<T> TableView<TableElements> ui.elements.InfoElement.makeTable (List< String > columnNames) package
Definition at line 68 of file InfoElement.java.
References ui.GUI.setInputText().
Referenced by ui.elements.InfoElement.init().
void ui.elements.InfoElement.setBindCommandList (String command)
Definition at line 102 of file InfoElement.java.
References ui.elements.InfoElement.update().
Referenced by ui.GUI.addCommandHistory().
void ui.elements.InfoElement.setBindVariableList (String command, double value)
Definition at line 97 of file InfoElement.java.
References ui.elements.InfoElement.update().
void ui.elements.InfoElement.update () private
Definition at line 107 of file InfoElement.java.
Referenced by ui.elements.InfoElement.setBindCommandList(), and ui.elements.InfoElement.setBindVariableList().
Member Data Documentation
ObservableList<TableElements> ui.elements.InfoElement.commands private
Initial value:
= FXCollections
            .observableArrayList()
Definition at line 25 of file InfoElement.java.
VBox ui.elements.InfoElement.myBaseNode private
Definition at line 21 of file InfoElement.java.
Referenced by ui.elements.InfoElement.getBaseNode().
GUI ui.elements.InfoElement.myGUI private
Definition at line 29 of file InfoElement.java.
List<TableView<TableElements> > ui.elements.InfoElement.myTables private
Definition at line 22 of file InfoElement.java.
Referenced by ui.elements.InfoElement.getTables().
TableView<TableElements> ui.elements.InfoElement.prevCommandsTable private
Definition at line 27 of file InfoElement.java.
ObservableList<TableElements> ui.elements.InfoElement.var private
Initial value:
= FXCollections
            .observableArrayList()
Definition at line 23 of file InfoElement.java.
TableView<TableElements> ui.elements.InfoElement.variablesTable private
Definition at line 28 of file InfoElement.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/ui/elements/InfoElement.java