slogo_team06: ui.SceneUpdater Class Reference
ui.SceneUpdater Class Reference
Public Member Functions
SceneUpdater (Stage s, Controller c)
void initGUI ()
void sendCommands (String input, String language)
void setOutputText (String outputText)
void setListBind (String type, ObservableList< TableElements > l)
Set< String > getPrevCommandList ()
void update (Observable o, Object arg)
void createTurtle (TurtleView tView)
void createNewWorkspace ()
void addCommandHistory (String input)
Private Attributes
final int SCREEN_WIDTH = 1000
final int SCREEN_HEIGHT = 600
GUI myGUI
Controller myController
Detailed Description
Definition at line 12 of file SceneUpdater.java.
Constructor & Destructor Documentation
ui.SceneUpdater.SceneUpdater (Stage s, Controller c)
Definition at line 19 of file SceneUpdater.java.
Member Function Documentation
void ui.SceneUpdater.addCommandHistory (String input)
Definition at line 79 of file SceneUpdater.java.
References ui.GUI.addCommandHistory().
Referenced by controller.Controller.addCommandHistory(), and controller.Controller.parseCommand().
void ui.SceneUpdater.createNewWorkspace ()
Definition at line 75 of file SceneUpdater.java.
References controller.Controller.createNewWorkspace().
Referenced by ui.GUI.createNewWorkspace().
void ui.SceneUpdater.createTurtle (TurtleView tView)
Sends the GUI's TurtleView, used to link it to corresponding Turtle in back-end
Returns
Definition at line 71 of file SceneUpdater.java.
References controller.Controller.createTurtle().
Referenced by ui.GUI.makeTurtleView().
Set<String> ui.SceneUpdater.getPrevCommandList ()
Definition at line 56 of file SceneUpdater.java.
References controller.Controller.getPrevCommandList().
void ui.SceneUpdater.initGUI ()
Definition at line 28 of file SceneUpdater.java.
References ui.GUI.initialize().
Referenced by controller.Controller.init().
void ui.SceneUpdater.sendCommands (String input, String language)
Sends inputed command from the GUI to the Controller
Parameters
input
language
Definition at line 38 of file SceneUpdater.java.
References controller.Controller.parseCommand().
Referenced by ui.GUI.parseCommand().
void ui.SceneUpdater.setListBind (String type, ObservableList< TableElements > l)
Definition at line 51 of file SceneUpdater.java.
References ui.GUI.bindTable().
void ui.SceneUpdater.setOutputText (String outputText)
Sends output text from the Controller to the GUI
Parameters
outputText
Definition at line 47 of file SceneUpdater.java.
References ui.GUI.setOutputText().
Referenced by controller.Controller.parseCommand().
void ui.SceneUpdater.update (Observable o, Object arg)
Definition at line 61 of file SceneUpdater.java.
Member Data Documentation
Controller ui.SceneUpdater.myController private
Definition at line 17 of file SceneUpdater.java.
GUI ui.SceneUpdater.myGUI private
Definition at line 15 of file SceneUpdater.java.
final int ui.SceneUpdater.SCREEN_HEIGHT = 600 private
Definition at line 14 of file SceneUpdater.java.
final int ui.SceneUpdater.SCREEN_WIDTH = 1000 private
Definition at line 13 of file SceneUpdater.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/ui/SceneUpdater.java