slogo_team06: command.turtle.ClearScreenCommand Class Reference
command.turtle.ClearScreenCommand Class Reference
Public Member Functions
ClearScreenCommand (Turtle t)
double calculateValue ()
Public Member Functions inherited from command.Command
abstract double calculateValue ()
Private Attributes
Turtle myTurtle
Detailed Description
erases turtle's trails and sends it to the home position returns the distance turtle moved
Author
GA
Definition at line 14 of file ClearScreenCommand.java.
Constructor & Destructor Documentation
command.turtle.ClearScreenCommand.ClearScreenCommand (Turtle t)
Definition at line 17 of file ClearScreenCommand.java.
Member Function Documentation
double command.turtle.ClearScreenCommand.calculateValue ()
Definition at line 21 of file ClearScreenCommand.java.
References model.Turtle.getX(), model.Turtle.getY(), model.Turtle.setClear(), model.Turtle.setHeading(), model.Turtle.setXY(), and model.Turtle.updateTurtleViewers().
Member Data Documentation
Turtle command.turtle.ClearScreenCommand.myTurtle private
Definition at line 15 of file ClearScreenCommand.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/command/turtle/ClearScreenCommand.java