slogo_team06: parser.CommandTreeNode Class Reference
parser.CommandTreeNode Class Reference
Public Member Functions
CommandTreeNode (String type, String name, double value, List< CommandTreeNode > children)
void add (CommandTreeNode newNode)
void clearChildren ()
void remove (CommandTreeNode newNode)
void setValue (double value)
double getValue ()
String getType ()
String getName ()
List< CommandTreeNode > getChildren ()
boolean equals (Object obj)
String toString ()
Private Attributes
String myType
String myName
Double myValue
List< CommandTreeNode > myChildren
Detailed Description
A TreeNode class for handling the commands
Author
Kei Yoshikoshi
Definition at line 12 of file CommandTreeNode.java.
Constructor & Destructor Documentation
parser.CommandTreeNode.CommandTreeNode (String type, String name, double value, List< CommandTreeNode > children)
Definition at line 18 of file CommandTreeNode.java.
Member Function Documentation
void parser.CommandTreeNode.add (CommandTreeNode newNode)
Definition at line 26 of file CommandTreeNode.java.
Referenced by parser.CommandCase.makingInstructionsCase(), parser.VariableCase.recurse(), parser.ListStartCase.recurse(), parser.GroupStartCase.recurse(), parser.ConstantCase.recurse(), and parser.CommandCase.recurse().
void parser.CommandTreeNode.clearChildren ()
Definition at line 30 of file CommandTreeNode.java.
boolean parser.CommandTreeNode.equals (Object obj)
Definition at line 64 of file CommandTreeNode.java.
List<CommandTreeNode> parser.CommandTreeNode.getChildren ()
Definition at line 59 of file CommandTreeNode.java.
References parser.CommandTreeNode.myChildren.
Referenced by command.control.AskCommand.AskCommand(), command.control.AskWithCommand.AskWithCommand(), command.control.DoTimesCommand.DoTimesCommand(), command.control.ForCommand.ForCommand(), command.control.IfCommand.IfCommand(), command.control.IfElseCommand.IfElseCommand(), model.TreeInterpreter.interpretTree(), command.control.RepeatCommand.RepeatCommand(), and command.control.TellCommand.TellCommand().
String parser.CommandTreeNode.getName ()
Definition at line 55 of file CommandTreeNode.java.
References parser.CommandTreeNode.myName.
Referenced by command.control.MakeVariableCommand.calculateValue(), parser.TreeGenerator.createCommands(), model.TreeInterpreter.executeCommand(), command.control.MakeUserInstructionCommand.MakeUserInstructionCommand(), parser.CommandCase.makingInstructionsCase(), parser.VariableCase.recurse(), parser.GroupStartCase.recurse(), parser.ListStartCase.recurse(), parser.ConstantCase.recurse(), parser.CommandCase.recurse(), and model.TreeInterpreter.update().
String parser.CommandTreeNode.getType ()
Definition at line 51 of file CommandTreeNode.java.
References parser.CommandTreeNode.myType.
Referenced by model.TreeInterpreter.executeCommand(), model.TreeInterpreter.interpretTree(), parser.CommandCase.makingInstructionsCase(), parser.VariableCase.recurse(), parser.GroupStartCase.recurse(), parser.ListStartCase.recurse(), parser.ConstantCase.recurse(), parser.CommandCase.recurse(), and model.TreeInterpreter.update().
double parser.CommandTreeNode.getValue ()
Definition at line 47 of file CommandTreeNode.java.
References parser.CommandTreeNode.myValue.
Referenced by command.control.AskWithCommand.calculateValue(), command.control.MakeVariableCommand.calculateValue(), command.control.RepeatCommand.calculateValue(), command.control.IfCommand.calculateValue(), command.control.IfElseCommand.calculateValue(), and controller.Controller.parseCommand().
void parser.CommandTreeNode.remove (CommandTreeNode newNode)
Definition at line 34 of file CommandTreeNode.java.
void parser.CommandTreeNode.setValue (double value)
Definition at line 43 of file CommandTreeNode.java.
Referenced by model.TreeInterpreter.executeCommand(), and model.TreeInterpreter.update().
String parser.CommandTreeNode.toString ()
Definition at line 71 of file CommandTreeNode.java.
Member Data Documentation
List<CommandTreeNode> parser.CommandTreeNode.myChildren private
Definition at line 16 of file CommandTreeNode.java.
Referenced by parser.CommandTreeNode.getChildren().
String parser.CommandTreeNode.myName private
Definition at line 14 of file CommandTreeNode.java.
Referenced by parser.CommandTreeNode.getName().
String parser.CommandTreeNode.myType private
Definition at line 13 of file CommandTreeNode.java.
Referenced by parser.CommandTreeNode.getType().
Double parser.CommandTreeNode.myValue private
Definition at line 15 of file CommandTreeNode.java.
Referenced by parser.CommandTreeNode.getValue().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/parser/CommandTreeNode.java