slogo_team06: parser.TreeWrapper Interface Reference
parser.TreeWrapper Interface Reference
Public Member Functions
void incrementIndex ()
void incrementListStartIndex ()
void incrementListEndIndex ()
int getIndex ()
void recurse (CommandTreeNode root)
void printTestStatements (String value, String type, String name)
Detailed Description
Interface that defines certain methods for users to access. Used to pass in TreeGenerator with limited method access
Author
Kei Yoshikoshi
Definition at line 10 of file TreeWrapper.java.
Member Function Documentation
int parser.TreeWrapper.getIndex ()
Implemented in parser.TreeGenerator.
Referenced by parser.CommandCase.initialize(), parser.VariableCase.recurse(), parser.ListStartCase.recurse(), parser.GroupStartCase.recurse(), parser.ConstantCase.recurse(), and parser.CommandCase.recurse().
void parser.TreeWrapper.incrementIndex ()
Implemented in parser.TreeGenerator.
Referenced by parser.CommandCase.initialize(), parser.VariableCase.recurse(), parser.ListStartCase.recurse(), parser.GroupStartCase.recurse(), parser.ConstantCase.recurse(), and parser.CommandCase.recurse().
void parser.TreeWrapper.incrementListEndIndex ()
Implemented in parser.TreeGenerator.
Referenced by parser.ListStartCase.recurse().
void parser.TreeWrapper.incrementListStartIndex ()
Implemented in parser.TreeGenerator.
Referenced by parser.ListStartCase.recurse().
void parser.TreeWrapper.printTestStatements (String value, String type, String name)
Implemented in parser.TreeGenerator.
Referenced by parser.CommandCase.initialize(), parser.CommandCase.makingInstructionsCase(), parser.VariableCase.recurse(), parser.GroupStartCase.recurse(), parser.ConstantCase.recurse(), parser.ListStartCase.recurse(), and parser.CommandCase.recurse().
void parser.TreeWrapper.recurse (CommandTreeNode root)
Implemented in parser.TreeGenerator.
Referenced by parser.CommandCase.initialize(), parser.CommandCase.makingInstructionsCase(), parser.GroupStartCase.recurse(), parser.ListStartCase.recurse(), and parser.CommandCase.recurse().
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/parser/TreeWrapper.java