slogo_team06: ui.GUI Class Reference
ui.GUI Class Reference
Public Member Functions
GUI (Stage stageIn, SceneUpdater sceneUpIn)
void initialize ()
TurtleView makeTurtleView (String imagePath)
void parseCommand ()
void setOutputText (String outputText)
void addCommandHistory (String input)
void setInputText (String inputText)
void bindTable (String type, ObservableList< TableElements > l)
void createNewWorkspace ()
Static Public Attributes
static final String DEFAULT_RESOURCE_PACKAGE = "resources.displayText/"
static final String DEFAULT_TURTLE_IMAGE_PATH = "/resources/images/turtleImage.png"
Private Member Functions
void setupKeyboardCommands ()
Private Attributes
Color DEFAULT_BACKGROUND = Color.FUCHSIA
ResourceBundle myResources
Scene myScene
Stage myStage
BorderPane myRoot
SceneUpdater mySceneUpdater
List< TurtleView > turtleViews
Pen myPen
IOElement ioPane
CanvasElement canvasPane
InfoElement infoPane
MenuBarElement menuPane
TPropertiesElement propertiesPane
String DEFAULT_LANG = "English"
String[] languages
Detailed Description
Definition at line 20 of file GUI.java.
Constructor & Destructor Documentation
ui.GUI.GUI (Stage stageIn, SceneUpdater sceneUpIn)
Definition at line 47 of file GUI.java.
Member Function Documentation
void ui.GUI.addCommandHistory (String input)
Definition at line 141 of file GUI.java.
References ui.elements.InfoElement.setBindCommandList().
Referenced by ui.SceneUpdater.addCommandHistory().
void ui.GUI.bindTable (String type, ObservableList< TableElements > l)
Definition at line 149 of file GUI.java.
References ui.elements.InfoElement.getTables().
Referenced by ui.SceneUpdater.setListBind().
void ui.GUI.createNewWorkspace ()
Definition at line 159 of file GUI.java.
References ui.SceneUpdater.createNewWorkspace().
Referenced by ui.elements.MenuBarElement.makeMenuBar().
void ui.GUI.initialize ()
Returns scene for this view so it can be added to stage.
Definition at line 57 of file GUI.java.
References ui.elements.CanvasElement.getBaseNode(), ui.elements.IOElement.getBaseNode(), ui.elements.InfoElement.getBaseNode(), ui.elements.MenuBarElement.getBaseNode(), ui.elements.CanvasElement.getCanvas(), ui.elements.TPropertiesElement.getMyBaseNode(), ui.GUI.makeTurtleView(), ui.GUI.myPen, ui.GUI.myStage, and ui.GUI.setupKeyboardCommands().
Referenced by ui.SceneUpdater.initGUI().
TurtleView ui.GUI.makeTurtleView (String imagePath)
Makes and returns a TurtleView object
Parameters
imagePath : The path of the Turtle Image
Returns
Definition at line 96 of file GUI.java.
References ui.SceneUpdater.createTurtle(), ui.elements.CanvasElement.getBaseNode(), ui.elements.InfoElement.getBaseNode(), ui.elements.CanvasElement.getCanvas(), and ui.GUI.myPen.
Referenced by ui.elements.TPropertiesElement.init(), and ui.GUI.initialize().
void ui.GUI.parseCommand ()
Sends a string slogo command through the Scene Updater and Controller, all the way to the back-end.
Definition at line 124 of file GUI.java.
References ui.elements.IOElement.getInputField(), ui.elements.MenuBarElement.getSelectedLanguage(), and ui.SceneUpdater.sendCommands().
Referenced by ui.elements.IOElement.init(), and ui.GUI.setupKeyboardCommands().
void ui.GUI.setInputText (String inputText)
Definition at line 145 of file GUI.java.
References ui.elements.IOElement.getInputField().
Referenced by ui.elements.InfoElement.makeTable().
void ui.GUI.setOutputText (String outputText)
Sets the output text field. Called from back-end (through controller)
Parameters
outputText
Definition at line 137 of file GUI.java.
References ui.elements.IOElement.getOutputField().
Referenced by ui.SceneUpdater.setOutputText().
void ui.GUI.setupKeyboardCommands () private
Set up keyboard commands
Definition at line 113 of file GUI.java.
References ui.GUI.parseCommand().
Referenced by ui.GUI.initialize().
Member Data Documentation
CanvasElement ui.GUI.canvasPane private
Definition at line 35 of file GUI.java.
Color ui.GUI.DEFAULT_BACKGROUND = Color.FUCHSIA private
Definition at line 24 of file GUI.java.
String ui.GUI.DEFAULT_LANG = "English" private
Definition at line 40 of file GUI.java.
final String ui.GUI.DEFAULT_RESOURCE_PACKAGE = "resources.displayText/" static
Definition at line 22 of file GUI.java.
final String ui.GUI.DEFAULT_TURTLE_IMAGE_PATH = "/resources/images/turtleImage.png" static
Definition at line 23 of file GUI.java.
Referenced by ui.elements.TPropertiesElement.init().
InfoElement ui.GUI.infoPane private
Definition at line 36 of file GUI.java.
IOElement ui.GUI.ioPane private
Definition at line 34 of file GUI.java.
String [] ui.GUI.languages private
Initial value:
= { "Chinese", "English", "French", "German",
                                  "Italian", "Japanese", "Korean", "Portuguese", "Russian",
                                  "Spanish" }
Definition at line 41 of file GUI.java.
MenuBarElement ui.GUI.menuPane private
Definition at line 37 of file GUI.java.
Pen ui.GUI.myPen private
Definition at line 32 of file GUI.java.
Referenced by ui.GUI.initialize(), and ui.GUI.makeTurtleView().
ResourceBundle ui.GUI.myResources private
Definition at line 26 of file GUI.java.
BorderPane ui.GUI.myRoot private
Definition at line 29 of file GUI.java.
Scene ui.GUI.myScene private
Definition at line 27 of file GUI.java.
SceneUpdater ui.GUI.mySceneUpdater private
Definition at line 30 of file GUI.java.
Stage ui.GUI.myStage private
Definition at line 28 of file GUI.java.
Referenced by ui.GUI.initialize().
TPropertiesElement ui.GUI.propertiesPane private
Definition at line 38 of file GUI.java.
List<TurtleView> ui.GUI.turtleViews private
Definition at line 31 of file GUI.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team06/repository/src/ui/GUI.java